# Docker Compose file that brings up containers necessary for NIBRS analytics using drill as the dimensional persistence layer
# To run:  docker-compose -f nibrs-analytics-drill-compose_jd.yaml up -d

version: '3.2'

networks:
  nibrs_analytics_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      -
       subnet: 172.15.0.0/16

services:
  zookeeper:
    container_name: zoo
    image: zookeeper
    restart: always
    networks:
      nibrs_analytics_nw:

  nibrs-analytics-drill:
    container_name: nibrs-analytics-drill
#    image: docker.pkg.github.com/ojbc/analytics/nibrs-drill:1.0
    image: ghcr.io/ojbc/analytics/nibrs-drill:1.0
    restart: always
    ports:
      - 8047:8047
    networks:
      nibrs_analytics_nw:
# uncomment this to change memory to 8G or whatever is needed
#    environment:
#      - DRILL_MAX_DIRECT_MEMORY=16G
    volumes:
      - /opt/data/nibrs/cde/:/nibrs/
